### ISSUE TITLE
TAKE A BREAK don't work correctly

### ISSUE THREAD

**Issue by BioHazardN7** [SilvDev/Real_Zoey_Unlock#1]
If you "TAKE A BREAK" playing as Zoe, it's impossible to return to the game as survivors.
[Screens](https://imgbox.com/g/Gm6tH2fPBX)

**Comment by SilvDev** [comment]
Suggest using: AFK and Join Team Commands Improved - https://forums.alliedmods.net/showpost.php?p=2719702
The option "Press to play as <char>" does not appear, but you can still join back.
